{{- if .Values.global.deployment.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "cspconsole.fullname" . }}-report-collector
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "cspconsole.fullname" . }}-report-collector
  minReplicas: {{ .Values.reportCollector.hpa.minReplicas }}
  maxReplicas: {{ .Values.reportCollector.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.reportCollector.hpa.averageUtilization }}
{{- end }}