apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "cspconsole.fullname" . }}-report-collector
  namespace: {{ required "Namespace not set" .Values.global.namespace }}
spec:
  minAvailable: {{ .Values.reportCollector.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ template "cspconsole.fullname" . }}-report-collector