apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "cspconsole.fullname" . }}-report-processor
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "cspconsole.fullname" . }}-report-processor
  minReplicas: {{ .Values.reportProcessor.hpa.minReplicas }}
  behavior:
    scaleDown:
      policies:
      - type: Percent
        value: 10
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Min
  maxReplicas: {{ .Values.reportProcessor.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.reportProcessor.hpa.averageUtilization }}
